DIV_NUM = 10
CROP_IMG = r"./cropped_images/" +  r"cropped_frame_"
CROP_RANGE = [215, 400, 85, 560]
SAVE_ARRAY_FILE = r"data/preprocessed_values.npy"
TRAIN_OUTPUT = r"data/train.txt" 
PREDICTIONS_OUTPUT = r"data/predictions.txt" 
TRAIN_FILE = r"data/train.mp4"
TEST_FILE = r"data/test.mp4"
INPUT_SHAPE = [10, 2]
MODEL_PATH = r"../speed_predictor_model"